language: java
jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - npm install -g angular-cli
  - npm install -g karma
  - npm install -g npm
  

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure: "cat /home/travis/build/moronicgeek/SwaggerCloud/server-ui/npm-debug.log"
